name: AWS Terraform Docker CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le code
        uses: actions/checkout@v4

      - name: Installer Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init sans backend
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Docker Build
        run: docker build -t aws-terraform-lab .
